name: main builder
on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/*.yml'
      - 'test/**'
      - 'hack/e2e/**'
      - 'hack/terraform/**'
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest]
        go: [1.18.x]
        include:
          - os: macos-latest
    runs-on: [self-hosted, linux, X64]
    name: build-test-${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Golang env
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Test
        run: go test -v ./...
      - name: Build
        run: ｜
          make clean
          make build -j8
      - name: test main actions success or not
        if: failure()
        run: |
          echo "main actions failure"
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          # curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"<at user_id=\"all\">All</at>Attention: dtm-actions failure: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} "}}' https://open.feishu.cn/open-apis/bot/v2/hook/${{ secrets.FEISHU_BOT_ID }}
